/* AI Trends — GitHub 高星项目库
   stars 为 2026-06-12 实测数据（GitHub API / 页面抓取）
   收录标准：①与 AI Agent 直接相关 ②生产可用或学习价值高 ③社区活跃 */
window.AIT_REPOS = {
  updated: "2026-06-12",
  cats: [
    { id: "autonomous", icon: "🦾", label: "自主智能体", blurb: "给它一个目标，自己跑完全程" },
    { id: "coding",     icon: "💻", label: "编程智能体", blurb: "写代码、修 bug、提 PR" },
    { id: "framework",  icon: "🏗️", label: "开发框架",   blurb: "工程师搭 Agent 用的脚手架" },
    { id: "lowcode",    icon: "🧩", label: "低代码编排", blurb: "拖拽画布搭工作流，PM 友好" },
    { id: "computer",   icon: "🖱️", label: "电脑操作",   blurb: "让 AI 像人一样用浏览器和软件" },
    { id: "memory",     icon: "🧠", label: "记忆与知识", blurb: "长期记忆、RAG、私有知识库" },
    { id: "infra",      icon: "🔌", label: "协议与基建", blurb: "MCP、本地推理、沙箱——给 Agent 修路" },
    { id: "ui",         icon: "🎨", label: "界面与体验", blurb: "Agent 产品的前端壳与交互组件" },
    { id: "learn",      icon: "📚", label: "学习资源",   blurb: "从零补课的体系化资料" }
  ],
  items: [
    { name: "OpenClaw", repo: "openclaw/openclaw", stars: 378254, cat: "autonomous",
      tagline: "本地优先的开源个人 AI 助理，数据不出自己的电脑",
      review: "<b>2026 年最大现象级项目</b>：半年从 9K 涨到 37.8 万星，逼得微软出了致敬产品 Scout。用 WhatsApp/Telegram 就能指挥，连接 50+ 工具。",
      fit: "想体验「数字员工」终极形态的人；研究个人 Agent 产品定位的 PM 必看" },
    { name: "AutoGPT", repo: "Significant-Gravitas/AutoGPT", stars: 184891, cat: "autonomous",
      tagline: "2023 年点燃 Agent 概念的鼻祖项目，现已转型 Agent 构建平台",
      review: "历史地位 > 当前实用性。理解 Agent 叙事演进的活化石，平台化转型后可低代码搭建持续运行的 Agent。",
      fit: "想了解 Agent 发展史的人；轻量自动化需求" },
    { name: "DeerFlow", repo: "bytedance/deer-flow", stars: 71010, cat: "autonomous",
      tagline: "字节开源的长程「超级 Agent」框架：调研、写代码、做内容",
      review: "大厂出品的 Deep Research 开源平替，中文生态友好。展示了「研究型 Agent」的完整工程实现。",
      fit: "想自建调研/报告自动化流水线的团队" },

    { name: "Gemini CLI", repo: "google-gemini/gemini-cli", stars: 105184, cat: "coding",
      tagline: "Google 官方终端编程 Agent，免费额度慷慨",
      review: "把 Gemini 直接带进终端，开源且免费额度大，是上手 Agentic Coding 成本最低的入口之一。",
      fit: "预算敏感的个人开发者；Google 生态用户" },
    { name: "OpenHands", repo: "All-Hands-AI/OpenHands", stars: 76516, cat: "coding",
      tagline: "开源版「AI 软件工程师」：读需求、写代码、跑测试、交付",
      review: "Devin 的开源对标，学术界和工业界共建，SWE-bench 长期霸榜的开源方案。",
      fit: "想自托管编程 Agent 的团队；研究 Agent 架构的工程师" },
    { name: "Cline", repo: "cline/cline", stars: 63075, cat: "coding",
      tagline: "VS Code 里的自主编程搭档，模型随意换",
      review: "IDE 内 Agent 的开源标杆：透明展示每一步操作并请求授权，「人机协作感」做得最好。",
      fit: "日常用 VS Code、想保留控制权的开发者" },
    { name: "SWE-agent", repo: "SWE-agent/SWE-agent", stars: 19485, cat: "coding",
      tagline: "普林斯顿出品：让模型自动修 GitHub issue 的学术标杆",
      review: "SWE-bench 同门，论文级严谨。星数不算高但引用极广，理解编程 Agent 原理的最佳教材。",
      fit: "想读懂编程 Agent 内部机制的人" },

    { name: "LangChain", repo: "langchain-ai/langchain", stars: 139082, cat: "framework",
      tagline: "最早也最大的 LLM 应用框架，生态无出其右",
      review: "争议与地位并存：被嫌弃过度封装，但文档、集成、人才储备仍是行业最全。已全面转向 Agent 工程平台。",
      fit: "需要「什么都有现成集成」的团队；招人容易是隐性优势" },
    { name: "AutoGen", repo: "microsoft/autogen", stars: 58887, cat: "framework",
      tagline: "微软的多智能体编程框架，研究气质浓厚",
      review: "多 Agent 对话编排的开创者，学术引用极多。微软已将其理念并入新的 Agent Framework。",
      fit: "多 Agent 协作研究；微软技术栈团队" },
    { name: "CrewAI", repo: "crewAIInc/crewAI", stars: 53293, cat: "framework",
      tagline: "「角色扮演式」多 Agent 框架：定角色、组团队、派任务",
      review: "API 设计最符合直觉——像组建真实团队一样写代码，新手友好度第一梯队。",
      fit: "首次尝试多 Agent 的团队；快速原型" },
    { name: "Agno", repo: "agno-agi/agno", stars: 40649, cat: "framework",
      tagline: "高性能全栈 Agent 平台，自带运行时与监控",
      review: "从框架卷到平台：构建、运行、管理一条龙，性能优化激进（毫秒级实例化）。",
      fit: "对性能和运维有要求的生产部署" },
    { name: "LangGraph", repo: "langchain-ai/langgraph", stars: 34482, cat: "framework",
      tagline: "用「状态图」精确控制 Agent 流程，LangChain 家的硬核担当",
      review: "把 Agent 当状态机建模：可暂停、可回溯、可人工介入。生产环境复杂 Agent 的事实标准。",
      fit: "对可控性要求高的生产级 Agent" },
    { name: "smolagents", repo: "huggingface/smolagents", stars: 27822, cat: "framework",
      tagline: "HuggingFace 的极简框架：千行代码、Agent 直接写 Python 行动",
      review: "「代码即行动」理念的代表，简洁到可以通读源码学原理。",
      fit: "想读源码理解 Agent 本质的人；轻量场景" },
    { name: "OpenAI Agents SDK", repo: "openai/openai-agents-python", stars: 27089, cat: "framework",
      tagline: "OpenAI 官方 Agent 框架：轻量、带 handoff 与 guardrail",
      review: "官方出品的克制设计，Swarm 的生产化版本。绑定 OpenAI 生态但抽象干净。",
      fit: "OpenAI 重度用户；需要官方长期维护保证的团队" },
    { name: "Google ADK", repo: "google/adk-python", stars: 20076, cat: "framework",
      tagline: "Google 官方 Agent 开发套件，原生支持 A2A 协议",
      review: "代码优先、对多 Agent 和评估工具支持完善，是 A2A 生态的参考实现。",
      fit: "Gemini/GCP 技术栈；关注 A2A 的团队" },
    { name: "MetaGPT", repo: "geekan/MetaGPT", stars: 68732, cat: "framework",
      tagline: "「一句话生成一个软件公司」：PM、架构师、工程师 Agent 流水线",
      review: "把 SOP 编码进多 Agent 协作的开创性项目，国人主导、论文获 ICLR oral。",
      fit: "研究多角色协作；对「AI 软件公司」叙事感兴趣的人" },

    { name: "n8n", repo: "n8n-io/n8n", stars: 192118, cat: "lowcode",
      tagline: "可自托管的工作流自动化平台，AI 节点深度集成",
      review: "<b>192K 星的隐形冠军</b>：先有成熟工作流底盘再长出 AI 能力，落地确定性远超纯 Agent 方案。",
      fit: "要把 AI 嵌进现有业务流程的团队；PM 自己就能搭" },
    { name: "Langflow", repo: "langflow-ai/langflow", stars: 149567, cat: "lowcode",
      tagline: "拖拽式 Agent/工作流画布，原型速度第一",
      review: "可视化编排里增长最快，画布体验流畅，一键导出 API。",
      fit: "快速验证想法的 PM 和设计师；演示场景" },
    { name: "Dify", repo: "langgenius/dify", stars: 144903, cat: "lowcode",
      tagline: "开源 LLM 应用开发平台：编排、知识库、监控一体",
      review: "国内团队出品、全球开花。企业自建「内部 AI 平台」的最常见选择，中文资料最全。",
      fit: "企业内部 AI 工具平台；中文团队首选" },
    { name: "Flowise", repo: "FlowiseAI/Flowise", stars: 53499, cat: "lowcode",
      tagline: "老牌可视化 Agent 搭建工具，模板生态丰富",
      review: "比 Langflow 更轻，社区模板多，适合小团队快速交付客户项目。",
      fit: "外包/咨询团队；轻量级需求" },

    { name: "browser-use", repo: "browser-use/browser-use", stars: 98362, cat: "computer",
      tagline: "让 Agent 操作浏览器的事实标准库",
      review: "DOM 路线的王者：比视觉方案快且稳，被无数下游产品内置。Web 自动化 Agent 的默认起点。",
      fit: "做 Web 自动化、数据采集、电商运营 Agent 的团队" },
    { name: "Skyvern", repo: "Skyvern-AI/skyvern", stars: 21892, cat: "computer",
      tagline: "视觉 + LLM 双路线的浏览器自动化，抗页面改版",
      review: "用计算机视觉理解页面而非依赖 DOM 结构，网站改版也不易失效，企业 RPA 替代场景表现好。",
      fit: "表单填报、流程自动化等 RPA 升级需求" },

    { name: "mem0", repo: "mem0ai/mem0", stars: 58377, cat: "memory",
      tagline: "给 AI 应用加「长期记忆」的通用记忆层",
      review: "记忆赛道头牌：自动抽取、更新、检索用户记忆，几行代码接入任意 Agent。",
      fit: "做个性化 AI 产品的团队——记忆是留存利器" },
    { name: "RAGFlow", repo: "infiniflow/ragflow", stars: 82499, cat: "memory",
      tagline: "深度文档理解驱动的开源 RAG 引擎，表格公式都啃得动",
      review: "把「文档解析」做到极致的 RAG：版面分析、表格还原远超普通切片，企业文档场景命中率高。",
      fit: "合同、报告、手册类重文档的企业知识库" },
    { name: "LlamaIndex", repo: "run-llama/llama_index", stars: 50088, cat: "memory",
      tagline: "数据接入与索引的老牌框架，现聚焦文档 Agent",
      review: "RAG 概念的早期布道者，连接器生态庞大，向「文档 Agent + OCR 平台」转型成功。",
      fit: "数据源杂、需要灵活索引策略的项目" },
    { name: "AnythingLLM", repo: "Mintplex-Labs/anything-llm", stars: 61463, cat: "memory",
      tagline: "开箱即用的本地全能 AI 工作台：聊天 + 知识库 + Agent",
      review: "非技术用户也能 10 分钟搭好「私有 ChatGPT + 知识库」，桌面版体验完整。",
      fit: "个人知识管理；数据敏感的小团队" },

    { name: "MCP Servers", repo: "modelcontextprotocol/servers", stars: 87080, cat: "infra",
      tagline: "MCP 协议官方服务器合集——Agent 工具生态的中央车站",
      review: "<b>看懂 Agent 生态先看这里</b>：每个 server 就是一种 Agent 能力。87K 星证明 MCP 已是事实标准。",
      fit: "所有 Agent 开发者；评估「能接什么工具」的 PM" },
    { name: "Ollama", repo: "ollama/ollama", stars: 173912, cat: "infra",
      tagline: "一行命令在本地跑大模型",
      review: "本地推理的国民级工具：`ollama run` 即起，开源模型试用的默认入口，隐私场景刚需。",
      fit: "想零成本试开源模型的所有人" },
    { name: "vLLM", repo: "vllm-project/vllm", stars: 82612, cat: "infra",
      tagline: "生产级大模型推理引擎，吞吐量标杆",
      review: "自建模型服务的事实标准：PagedAttention 开创高效推理，几乎所有模型厂的部署文档都默认它。",
      fit: "自部署开源模型对外服务的团队" },
    { name: "Firecrawl", repo: "firecrawl/firecrawl", stars: 131608, cat: "infra",
      tagline: "把任意网页变成干净的 LLM 可用数据",
      review: "「Agent 的眼睛」：抓取、渲染、转 Markdown 一条龙，是无数研究型 Agent 的底层依赖。",
      fit: "需要联网获取信息的任何 Agent 项目" },
    { name: "Daytona", repo: "daytonaio/daytona", stars: 72461, cat: "infra",
      tagline: "为 AI 生成代码准备的安全弹性沙箱",
      review: "Agent 基建赛道代表：毫秒级启动隔离环境，让 Agent 放心跑它自己写的代码。",
      fit: "做编程/数据分析 Agent、需要执行环境隔离的团队" },

    { name: "Lobe Chat", repo: "lobehub/lobe-chat", stars: 78531, cat: "ui",
      tagline: "颜值天花板的开源 AI 聊天框架，插件与多模型齐备",
      review: "把「好看」做成核心竞争力的范本，主题、插件市场、知识库俱全，自建 ChatGPT 替代的首选。",
      fit: "想快速拥有体面 AI 入口的个人与团队；学习 AI 产品交互设计" },
    { name: "CopilotKit", repo: "CopilotKit/CopilotKit", stars: 34750, cat: "ui",
      tagline: "给自家产品嵌入 AI 副驾的 React 组件库",
      review: "解决「我的 SaaS 怎么加 AI」的最后一公里：聊天侧栏、行内补全、Agent 状态 UI 全是现成组件。",
      fit: "要给现有产品加 AI 能力的前端团队" },

    { name: "AI Agents for Beginners", repo: "microsoft/ai-agents-for-beginners", stars: 67034, cat: "learn",
      tagline: "微软官方 12 课 Agent 入门，配代码与视频",
      review: "体系化入门的最佳起点：从概念到 RAG 到多 Agent，每课带可跑示例，中文翻译齐全。",
      fit: "脱产后补课的第一站——强烈推荐先刷这个" },
    { name: "Awesome LLM Apps", repo: "Shubhamsaboo/awesome-llm-apps", stars: 114310, cat: "learn",
      tagline: "100+ 个可直接运行的 Agent/RAG 应用合集",
      review: "「抄作业」宝库：每个应用都能克隆即跑，覆盖几乎所有主流场景与技术组合。",
      fit: "学完概念想动手的人；找产品灵感的 PM" },
    { name: "Prompt Engineering Guide", repo: "dair-ai/Prompt-Engineering-Guide", stars: 75550, cat: "learn",
      tagline: "提示词与上下文工程的百科全书，持续更新",
      review: "从基础技巧到 Agent、RAG 论文索引全覆盖，多语言版本，学术与实战兼顾。",
      fit: "想系统理解「怎么和模型说话」的所有人" }
  ]
};
