/* AI Trends — Agent Skills 技能库
   收录标准：①真实存在、可被 Agent 调用 ②有明确用途、非玩具 ③来源可考（官方/平台/社区）
   注：Skill 多为开箱即用能力，没有 star 概念，故以「来源」标注其出处与可信度。
   更新方法见 README.md。 */
window.AIT_SKILLS = {
  updated: "2026-06-15",
  // 给非技术读者的一段话：什么是 Skill
  intro: "<b>Agent Skill</b> = 一个装着 <code>SKILL.md</code>（说明书）+ 脚本/模板/资源的文件夹，告诉 Agent「遇到某类任务该怎么做、用什么工具、注意什么」。模型按需加载（渐进式披露，不占上下文），同一个 skill 在 Claude App / Claude Code / API 之间通用。2025 年 10 月 Anthropic 正式推出，被称为 Agent 的「可复用专长」——相当于给通才 AI 外挂一身随取随用的手艺。<br>想找更多：官方示例库 <code>github.com/anthropics/skills</code>，各平台（Cloudflare、GSAP、Figma）也在把自家最佳实践打包成 skill。",
  cats: [
    { id: "office",  icon: "📄", label: "文档办公",   blurb: "把 Word/PDF/PPT/Excel 读懂、改对、做漂亮" },
    { id: "design",  icon: "🎨", label: "设计创意",   blurb: "品牌、海报、UI、幻灯片——一句话出活" },
    { id: "figma",   icon: "🖼️", label: "Figma 桥接", blurb: "设计稿 ↔ 代码双向打通" },
    { id: "motion",  icon: "✨", label: "前端动效",   blurb: "GSAP 一族：滚动、时间线、性能" },
    { id: "cloud",   icon: "☁️", label: "云与后端",   blurb: "Cloudflare 全家桶：Workers / 存储 / Agent" },
    { id: "devflow", icon: "🛠️", label: "开发提效",   blurb: "评审、验证、简化、一键跑起来" },
    { id: "meta",    icon: "🧠", label: "元技能·造技能", blurb: "造 skill、记忆、调度、调 API" },
    { id: "example", icon: "🧭", label: "实战示例",   blurb: "官方示例：从中学怎么写自己的 skill" }
  ],
  items: [
    /* ---------- 文档办公 ---------- */
    { name: "docx", cat: "office", source: "官方", gh: "anthropics/skills",
      tagline: "Word 文档的全自动秘书：生成、读取、改写、批注",
      what: "创建带目录/页眉页脚/页码/信笺抬头的专业 Word；提取与重组 .docx 内容；查找替换、插入替换图片、处理修订与批注。",
      why: "PM 写 PRD / 周报 / 对外文档不用再手搓格式，把「内容」交给 AI，「排版」一并搞定。" },
    { name: "pdf", cat: "office", source: "官方", gh: "anthropics/skills",
      tagline: "PDF 瑞士军刀：读、合、拆、填表、OCR",
      what: "读取/抽取文字表格、合并拆分、旋转加水印、填写表单、加解密、抽图，以及对扫描件做 OCR 变可搜索。",
      why: "合同、报告、扫描件这类「只读黑盒」变成可处理的数据，调研归档效率立竿见影。" },
    { name: "pptx", cat: "office", source: "官方", gh: "anthropics/skills",
      tagline: "幻灯片代笔：建 deck、读 deck、套模板",
      what: "从零做演示/路演 deck，或读取现有 .pptx 抽文字、改版式、处理讲者备注与批注、合并拆分。",
      why: "评审、汇报、融资材料从「半天排版」压到「一句话生成初稿」，再人工精修。" },
    { name: "xlsx", cat: "office", source: "官方", gh: "anthropics/skills",
      tagline: "表格管家：公式、图表、清洗脏数据",
      what: "打开/读写 .xlsx/.csv，加列算公式、格式化、画图，把错位表头/垃圾行的脏数据整理成规整表。",
      why: "运营和数据类工作最高频的「Excel 苦力活」交给 AI，且产出仍是可继续编辑的真表格。" },

    /* ---------- 设计创意 ---------- */
    { name: "ckm-design", cat: "design", source: "社区",
      tagline: "综合设计中枢：logo / CIP / banner / 图标 / 社媒图",
      what: "品牌识别、logo（55 风格，Gemini 生成）、企业识别系统（50 项交付物 + 样机）、HTML 演示、banner（22 风格）、SVG 图标、多平台社媒图一条龙。",
      why: "个人或小团队没有设计外包预算时，用一个 skill 撑起一整套品牌视觉。" },
    { name: "ckm-brand", cat: "design", source: "社区",
      tagline: "品牌守门人：声音、视觉、信息框架、合规",
      what: "定义品牌语气、视觉识别、信息框架与资产管理，对产出内容做品牌一致性校验。",
      why: "保证所有对外物料口径统一——尤其多人协作时不跑偏。" },
    { name: "ckm-banner-design", cat: "design", source: "社区",
      tagline: "多平台 banner 工厂：22 风格、社媒/广告/web/print",
      what: "为 Facebook/X/LinkedIn/YouTube/Instagram/Google Display/网站 hero/印刷 出多套艺术方向 + AI 生成视觉。",
      why: "投放与活动需要的尺寸×风格组合一次拉满，省掉来回比稿。" },
    { name: "ckm-design-system", cat: "design", source: "社区",
      tagline: "设计系统骨架：三层 token + 组件规范",
      what: "primitive→semantic→component 三层 token、CSS 变量、间距/字阶、组件规范与战略型幻灯片。",
      why: "把「好看」沉淀成「系统」，团队复用不返工——做 B 端/SaaS 的隐性护城河。" },
    { name: "ckm-slides", cat: "design", source: "社区",
      tagline: "战略型 HTML 演示：Chart.js + design token",
      what: "用 design token、响应式布局、文案公式与情境化幻灯片策略，生成带图表的 HTML 演示。",
      why: "汇报不止「好看」，还讲究叙事结构与数据可视化的策略性。" },
    { name: "ckm-ui-styling", cat: "design", source: "社区",
      tagline: "无障碍 UI 速成：shadcn/ui + Tailwind",
      what: "用 shadcn/ui（Radix + Tailwind）搭可访问组件、暗色模式、主题定制与画布视觉。",
      why: "前端从 0 到「体面且无障碍」最短路径，设计与实现一步到位。" },
    { name: "ui-ux-pro-max", cat: "design", source: "社区",
      tagline: "UI/UX 设计智库：50+ 风格 / 161 配色 / 57 字体配对",
      what: "覆盖 161 种产品类型、99 条 UX 准则、25 种图表、10 个技术栈（React/Vue/Svelte/SwiftUI/Flutter…），可规划/构建/评审/优化 UI。",
      why: "做设计决策时的「随身顾问」——配色字体不靠玄学，有体系可依。" },

    /* ---------- Figma 桥接 ---------- */
    { name: "figma-generate-design", cat: "figma", source: "官方", gh: "figma/skills",
      tagline: "代码 → Figma：把 app 页面翻译进设计稿",
      what: "把一个页面/布局基于现有设计系统生成为 Figma 设计（design-to-Figma）。",
      why: "实现先行的团队，能反向补齐设计稿，保持设计-代码同源。" },
    { name: "figma-generate-library", cat: "figma", source: "官方", gh: "figma/skills",
      tagline: "代码 → 设计系统：从代码搭 Figma 组件库",
      what: "依据代码库构建 Figma 设计系统 / 设计 token / 组件库。",
      why: "把工程里已有的组件资产「上岸」成设计师可用的库。" },
    { name: "figma-code-connect", cat: "figma", source: "官方", gh: "figma/skills",
      tagline: "组件对账：Figma 组件 ↔ 代码组件映射",
      what: "把 Figma 组件与代码组件建立 Code Connect 映射，互相引用。",
      why: "设计交付到落地不再「看图复刻」，组件一一对应、改一处同步。" },
    { name: "figma-use", cat: "figma", source: "官方", gh: "figma/skills",
      tagline: "Figma 协作前置必读：use_figma 的规范",
      what: "调用 Figma 写入能力前的强制规范与最佳实践（避免破坏既有文件结构）。",
      why: "让 AI 动 Figma 文件时「先懂规矩再下手」，降低误操作。" },

    /* ---------- 前端动效 ---------- */
    { name: "gsap-core", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "动效核心 API：to / from / timeline / ease",
      what: "gsap.to()/from()/fromTo()、缓动、时长、stagger、matchMedia（响应式 + 尊重 prefers-reduced-motion）。框架无关，任意 JS 可用。",
      why: "Web 动画的工业标准，Webflow 交互即由它驱动——会一个库走遍各框架。" },
    { name: "gsap-scrolltrigger", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "滚动驱动：parallax、pin、scrub",
      what: "滚动联动动画、区块固定（pinning）、进度跟随（scrub）、触发器。",
      why: "现在「会讲故事」的官网/落地页核心套路，作品集质感的关键。" },
    { name: "gsap-timeline", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "时间线编排：序列、嵌套、位置参数",
      what: "gsap.timeline()、position 参数、嵌套与回放控制，精确编排多段动画。",
      why: "复杂转场/开场动画不靠堆 setTimeout，可维护可微调。" },
    { name: "gsap-react", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "React/Next 集成：useGSAP + 自动清理",
      what: "useGSAP hook、refs、gsap.context()、卸载时清理。",
      why: "React 里做动画不内存泄漏、不闪烁的官方姿势。" },
    { name: "gsap-plugins", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "插件全家：Flip / Draggable / SplitText / Smoother",
      what: "ScrollSmoother、Flip、Draggable、Inertia、Observer、SplitText、ScrambleText、SVG 与物理插件的注册与用法。",
      why: "平滑滚动、文字拆分动画、拖拽——高级交互的现成弹药库。" },
    { name: "gsap-performance", cat: "motion", source: "GSAP", gh: "greensock/GSAP",
      tagline: "动效性能：稳 60fps、不卡顿",
      what: "优先 transform、避免布局抖动、will-change、批处理。",
      why: "动画好看还得不掉帧——低端机和移动端的体验底线。" },

    /* ---------- 云与后端 ---------- */
    { name: "cloudflare", cat: "cloud", source: "Cloudflare", gh: "cloudflare/cloudflare-docs",
      tagline: "Cloudflare 平台总技能：Workers / 存储 / AI",
      what: "Workers、Pages、KV、D1、R2、Workers AI、Vectorize、Agents、WAF、Terraform/Pulumi——任意 Cloudflare 开发任务，优先查官方文档而非记忆。",
      why: "你的作品集后端就是这套（Workers+D1+Cron），这是「全栈不养服务器」的现实路径。" },
    { name: "agents-sdk", cat: "cloud", source: "Cloudflare", gh: "cloudflare/agents",
      tagline: "在 Workers 上建有状态 Agent / 工作流 / MCP",
      what: "Agent 类、状态管理、可调用 RPC、Workflows 持久执行、队列重试、可观测性、React hooks、定时任务、WebSocket 实时、MCP server。",
      why: "把「真实有记忆、能定时干活」的 Agent 跑在边缘——MY App 世界持久化正是这条路。" },
    { name: "durable-objects", cat: "cloud", source: "Cloudflare", gh: "cloudflare/workerd",
      tagline: "有状态协调：聊天室 / 多人 / 预订",
      what: "Durable Objects 做强一致协调，RPC 方法、SQLite 存储、alarms、WebSocket，含 wrangler 配置与 Vitest 测试。",
      why: "需要「同一份状态被很多人实时读写」时的标准答案（如全局版本号、在线协作）。" },
    { name: "sandbox-sdk", cat: "cloud", source: "Cloudflare", gh: "cloudflare/sandbox-sdk",
      tagline: "安全沙箱：放心跑 AI 写的代码",
      what: "Sandbox SDK 生命周期、命令、文件、代码解释器、预览 URL，用于 AI 代码执行 / 代码解释器 / CI。",
      why: "让 Agent 执行自己生成的代码而不威胁主系统——编程类 Agent 的安全底座。" },
    { name: "wrangler", cat: "cloud", source: "Cloudflare", gh: "cloudflare/workers-sdk",
      tagline: "Workers 命令行：部署与资源管理",
      what: "部署/开发 Workers，管理 KV、R2、D1、Vectorize、Queues、Workflows、Secrets 等，运行前先确认语法与最佳实践。",
      why: "一条命令把代码推上全球边缘——本地到生产的最后一公里。" },
    { name: "workers-best-practices", cat: "cloud", source: "Cloudflare", gh: "cloudflare/cloudflare-docs",
      tagline: "Workers 生产体检：揪出反模式",
      what: "审查/编写 Workers 代码，对照生产最佳实践检查流式、悬空 promise、全局状态、密钥、绑定、可观测性等坑。",
      why: "新手最容易踩的「能跑但不稳」问题，上线前先过一遍。" },
    { name: "cloudflare-email-service", cat: "cloud", source: "Cloudflare", gh: "cloudflare/cloudflare-docs",
      tagline: "事务邮件收发 + 送达率（SPF/DKIM/DMARC）",
      what: "用 Workers 绑定或 REST API 发收事务邮件、邮件路由、Agents SDK 邮件处理，含送达率与认证配置。",
      why: "产品的注册验证 / 通知邮件，不接第三方也能在自家后端搞定。" },
    { name: "turnstile-spin", cat: "cloud", source: "Cloudflare", gh: "cloudflare/cloudflare-docs",
      tagline: "一键接入人机验证（CAPTCHA 平替）",
      what: "端到端接 Turnstile：扫代码库、建 widget、部署 siteverify Worker、写前端片段、校验、固化。",
      why: "表单/登录防机器人，不打扰真人、隐私友好——比传统验证码体验好。" },

    /* ---------- 开发提效 ---------- */
    { name: "code-review", cat: "devflow", source: "官方",
      tagline: "改动评审：抓 bug + 提简化/复用/效率",
      what: "按 low→max 力度审当前 diff 的正确性 bug 与清理项，可把发现作为 PR 行内评论或直接改进工作区。",
      why: "提交前的「第二双眼睛」，把低级错误挡在合并之前。" },
    { name: "security-review", cat: "devflow", source: "官方",
      tagline: "安全评审：当前分支的待提交改动",
      what: "对 pending 改动做安全审查，识别注入、鉴权、密钥泄露等风险。",
      why: "你的后端涉及鉴权与密钥，每次动它之前最好让它扫一遍。" },
    { name: "verify", cat: "devflow", source: "官方",
      tagline: "真跑验证：改动是否如预期",
      what: "真正启动 app、观察行为来验证一次改动/修复是否生效，而非只看测试。",
      why: "「我以为修好了」和「确实修好了」之间，差一个 verify。" },
    { name: "run", cat: "devflow", source: "官方",
      tagline: "把 app 跑起来：截图看真实效果",
      what: "启动并驱动本项目 app，确认改动在真实应用里生效（优先用项目已有的启动方式）。",
      why: "静态站/沙盒预览/本地服务，一句话拉起来看效果。" },
    { name: "simplify", cat: "devflow", source: "官方",
      tagline: "只做减法：复用 / 简化 / 效率清理",
      what: "审查改动里的复用、简化、效率、抽象层级问题并直接应用修复（只管质量，不找 bug）。",
      why: "代码越写越乱时的「整理收纳」，让后人（和未来的你）少受罪。" },
    { name: "init", cat: "devflow", source: "官方",
      tagline: "给代码库写说明书：生成 CLAUDE.md",
      what: "扫描代码库，初始化一份 CLAUDE.md 文档，沉淀结构、约定与命令。",
      why: "每个新项目第一步——让 AI（和协作者）一上来就懂你的工程。" },
    { name: "web-perf", cat: "devflow", source: "官方",
      tagline: "网页性能审计：Core Web Vitals",
      what: "用 Chrome DevTools MCP 测 LCP/INP/CLS 等指标，找渲染阻塞、网络依赖链、布局抖动、缓存与无障碍问题。",
      why: "页面慢在哪、怎么快——给数据不给玄学，作品集/落地页加分项。" },

    /* ---------- 元技能·造技能 ---------- */
    { name: "skill-creator", cat: "meta", source: "官方", gh: "anthropics/skills",
      tagline: "造 skill 的 skill：从零创建、评测、优化触发",
      what: "从零创建/编辑/优化 skill，跑 eval 测试、做方差分析基准、优化 description 让触发更准。",
      why: "把你重复对 AI 说的话固化成一次性写好的专长——元能力，越用越值。" },
    { name: "claude-api", cat: "meta", source: "官方",
      tagline: "Claude API / SDK 速查：模型、价格、工具、缓存",
      what: "模型 id、定价、参数、流式、工具调用、MCP、Agents、提示缓存、token 计数、模型迁移的权威参考。",
      why: "自己接 LLM 时不必翻文档——模型选型/限流/缓存一处查清。" },
    { name: "schedule", cat: "meta", source: "官方",
      tagline: "定时任务：「每天早上跑一次」",
      what: "创建/更新自动运行的定时任务（「每天」「每小时」「下午三点」这类自然语言）。",
      why: "这正是你问的「每天自动更新」该用的能力——把重复动作交给日程。" },
    { name: "consolidate-memory", cat: "meta", source: "官方",
      tagline: "记忆整理：合并重复、修正过时、剪枝",
      what: "对 AI 的记忆文件做反思式整理：合并重复、修正陈旧事实、精简索引。",
      why: "长期协作后记忆会变乱，定期「断舍离」让 AI 记得准。" },
    { name: "update-config", cat: "meta", source: "官方",
      tagline: "配置 Claude Code：权限 / hooks / 环境变量",
      what: "通过 settings.json 配置自动化行为（hooks）、权限、环境变量，排查 hook 问题。",
      why: "「以后每次 X 都自动做 Y」这类需求，必须落到 hooks 才生效。" },
    { name: "setup-cowork", cat: "meta", source: "官方",
      tagline: "Cowork 引导设置：装插件、连工具",
      what: "按角色匹配安装插件、连接你的工具、试用一个 skill 的引导流程。",
      why: "从「裸装」到「趁手」的开箱向导，少走弯路。" },

    /* ---------- 实战示例（学怎么写 skill） ---------- */
    { name: "artifacts-builder", cat: "example", source: "官方", gh: "anthropics/skills",
      tagline: "示例：构建交互式 Artifacts 前端产物",
      what: "Anthropic 官方示例 skill，演示如何生成可交互的前端 artifact。",
      why: "想学「一个完整 skill 长什么样」，从官方示例照着拆最快。" },
    { name: "mcp-builder", cat: "example", source: "官方", gh: "anthropics/skills",
      tagline: "示例：构建 MCP server，把工具接进 Agent",
      what: "官方示例 skill，指导从零搭一个 MCP server，暴露工具/资源给 Agent 生态。",
      why: "MCP 是 Agent 接外部能力的事实标准，这是动手的最佳起点。" },
    { name: "canvas-design", cat: "example", source: "官方", gh: "anthropics/skills",
      tagline: "示例：在画布上做视觉 / 海报",
      what: "官方示例 skill，演示用画布生成视觉设计与海报类产物。",
      why: "看官方怎么把「视觉生成」这类模糊任务写成稳定流程。" },
    { name: "webapp-testing", cat: "example", source: "官方", gh: "anthropics/skills",
      tagline: "示例：自动化测试 web 应用",
      what: "官方示例 skill，演示对 web app 做端到端/交互测试的标准做法。",
      why: "把「测试」这种纪律性工作固化成 skill，质量更稳。" },
    { name: "slack-gif-creator", cat: "example", source: "官方", gh: "anthropics/skills",
      tagline: "示例：做 Slack 用的 GIF",
      what: "官方示例 skill，演示生成可在 Slack 使用的 GIF 动图。",
      why: "麻雀虽小——是理解「轻量 skill 怎么打包资源」的好样本。" }
  ]
};
