/* AI Trends — 模型图鉴数据
   数据截至 2026-06-12；价格为官方 API 牌价（USD / 每百万 token，输入/输出）
   信息来源：官方发布 + llm-stats / OpenRouter / 媒体多源交叉验证 */
window.AIT_MODELS = {
  updated: "2026-06-12",
  note: "优缺点按使用视角撰写，不替任何厂商说话；分数与价格随时会变，以官方为准。",
  picks: [
    { scene: "写代码 / 编程 Agent", rec: "Claude Fable 5 · GPT-5.5", alt: "平替：DeepSeek V4 Pro、Mistral Medium 3.5" },
    { scene: "超长文档 / 整库分析", rec: "Opus 4.8 · Qwen 3.7 Plus（1M）", alt: "开源极限：Llama 4 Scout（10M）" },
    { scene: "成本敏感 / 大批量调用", rec: "Grok 4.1 Fast · Mistral Small 4", alt: "开源自部署：DeepSeek V4 Pro" },
    { scene: "本地 / 私有化部署", rec: "DeepSeek V4 · Mistral Large 3", alt: "轻量：Gemma 4、Ministral 3" },
    { scene: "中文与本土生态", rec: "Qwen 3.7 · Kimi K2.6 · 豆包 2.0", alt: "政企：GLM-5.1、星火 X2" },
    { scene: "多模态理解与生成", rec: "Gemini 3.1 Pro · 豆包 2.0", alt: "全模态国产：文心 5.0" }
  ],
  groups: [
    { id: "flagship", icon: "👑", label: "海外旗舰·闭源" },
    { id: "openintl", icon: "🌍", label: "海外开源" },
    { id: "china",    icon: "🇨🇳", label: "中国队" },
    { id: "light",    icon: "⚡", label: "特化与轻量" }
  ],
  items: [
    /* ---------- 海外旗舰 ---------- */
    { name: "GPT-5.5", vendor: "OpenAI", group: "flagship", access: "闭源", date: "2026 春",
      pos: "综合智能的标杆之一，Instant / Pro 分层覆盖全场景",
      specs: ["上下文 922K", "$5 / $30", "Pro · Instant 双轨"],
      pros: ["通用推理与知识广度第一梯队", "生态与第三方集成最大", "路由机制自动分配快慢思考"],
      cons: ["旗舰定价，批量场景烧钱", "更新节奏快，行为漂移需回归测试", "Agent 长程执行稳定性不及专攻编码的对手"],
      fit: "通用旗舰需求、面向大众的 C 端产品" },
    { name: "Claude Fable 5", vendor: "Anthropic", group: "flagship", access: "闭源", date: "2026.06.09",
      pos: "当前编码与长程 Agent 任务的事实标杆",
      specs: ["Claude Code 原生", "长程任务优化", "MCP 亲和"],
      pros: ["复杂工程任务的执行稳定性突出", "工具调用 / Agent 编排能力最强档", "发布即进生产工具，工程化成熟"],
      cons: ["旗舰价格", "多模态生成能力不是重点", "面向开发者，大众产品形态较少"],
      fit: "编程 Agent、企业级自动化、长链路任务" },
    { name: "Claude Opus 4.8", vendor: "Anthropic", group: "flagship", access: "闭源", date: "2026.05.28",
      pos: "1M 上下文 + 写作质感，长文档之王",
      specs: ["上下文 1M", "$6.25 / $25"],
      pros: ["百万上下文整库 / 整书直读", "文字质感与审美公认最佳", "比上代更便宜"],
      cons: ["速度中庸", "超长上下文下成本仍可观"],
      fit: "长文档分析、高质量写作、知识工作" },
    { name: "Gemini 3.1 Pro", vendor: "Google", group: "flagship", access: "闭源", date: "2026 初",
      pos: "多模态最全能的旗舰，搜索与全家桶加持",
      specs: ["原生多模态", "Google 生态整合"],
      pros: ["图像 / 音频 / 视频理解全面", "与搜索、Workspace 深度联动", "免费额度慷慨"],
      cons: ["AI Studio / Vertex 双轨 API 体验割裂", "版本迭代快，行为一致性一般"],
      fit: "多模态应用、信息密集型工作流" },
    { name: "Grok 4.3", vendor: "xAI", group: "flagship", access: "闭源", date: "2026 春",
      pos: "推理密度高、带 X 实时数据的「莽派」旗舰",
      specs: ["~500B 参数", "X 实时数据", "Heavy 档 $300/月"],
      pros: ["实时信息接入独一份", "多智能体架构激进试验（4/16-agent）", "迭代速度极快"],
      cons: ["4 月大宕机暴露工程稳定性风险", "输出风格不稳，企业合规顾虑多", "高端档价格门槛高"],
      fit: "实时信息场景、追新能力的个人用户" },
    { name: "Muse Spark", vendor: "Meta", group: "flagship", access: "闭源", date: "2026.04.08",
      pos: "Meta 放弃开源后的首个闭源旗舰",
      specs: ["仅 meta.ai 可用", "AAII 52 分"],
      pros: ["社交产品矩阵的免费分发入口", "Meta 超级智能实验室全力投入"],
      cons: ["跑分落后同期旗舰（GPT-5.4 / Gemini 3.1 为 57）", "无 API 权重，开发者无从下手", "弃开源重创社区信任"],
      fit: "暂只值得观察，不建议押注" },
    { name: "MAI-1 系列", vendor: "Microsoft", group: "flagship", access: "闭源", date: "2026.06.02",
      pos: "微软的自研备份：MAI-Code-1-Flash + MAI-Thinking-1",
      specs: ["Code / Thinking 双线", "M365 生态原生"],
      pros: ["微软生态与企业合规天然加分", "降低对 OpenAI 的依赖，议价工具"],
      cons: ["能力暂逊一线旗舰", "定位「备胎」，投入连续性待观察"],
      fit: "深度微软栈企业的备选项" },
    { name: "Mistral Medium 3.5", vendor: "Mistral", group: "flagship", access: "闭源", date: "2026 春 (preview)",
      pos: "欧洲独苗的旗舰：单模型融合推理 / 编码 / 指令",
      specs: ["128B dense", "上下文 256K", "SWE-bench Verified 77.6%"],
      pros: ["编码实测分数凶悍，超自家 Devstral 2", "欧洲数据主权与合规优势", "Le Chat / Vibe CLI 默认模型"],
      cons: ["生态与工具链远小于美中两强", "多模态能力一般"],
      fit: "欧洲合规需求、编码为主的团队" },

    /* ---------- 海外开源 ---------- */
    { name: "Llama 4（Scout / Maverick）", vendor: "Meta", group: "openintl", access: "开源", date: "2025.04",
      pos: "10M 上下文的开源纪录保持者，但已一年未更新",
      specs: ["Scout 10M 上下文", "Maverick 1M / 400B MoE"],
      pros: ["Scout 上下文长度开源之最", "部署生态与工具链成熟", "许可宽松、社区资料海量"],
      cons: ["一年未迭代，性能被国产开源超越", "Behemoth 永久跳票", "Meta 重心已转闭源，前途不明"],
      fit: "存量 Llama 技术栈、超长上下文实验" },
    { name: "Mistral Large 3", vendor: "Mistral", group: "openintl", access: "开源", date: "2025.12",
      pos: "西方阵营最大的开源 MoE（675B / 41B 激活）",
      specs: ["Apache 2.0", "675B MoE", "MMLU-Pro 73.1"],
      pros: ["大体量开源 + 最宽松许可", "LMArena 开源非推理类第 2", "基座 / 指令双版本齐全"],
      cons: ["输出速度慢（~38 t/s）", "Agent 指标不如同期国产开源"],
      fit: "需要宽松许可的自部署与二次训练" },
    { name: "Gemma 4 系列", vendor: "Google", group: "openintl", access: "开源", date: "2026.05",
      pos: "为 Agent 工作流设计的开源中杯",
      specs: ["12B 起多尺寸", "Agent 工作流优化"],
      pros: ["大厂品质 + 免费可微调", "面向 Agent 场景专门调教", "与 Gemini 生态平滑衔接"],
      cons: ["体量小，复杂任务上限明显", "本质是 Gemini 的获客漏斗"],
      fit: "预算有限的 Agent 原型、本地小模型" },

    /* ---------- 中国队 ---------- */
    { name: "DeepSeek V4 Pro", vendor: "深度求索", group: "china", access: "开源", date: "2026 春",
      pos: "开源逼近闭源旗舰的里程碑，性价比屠夫",
      specs: ["MIT 协议", "输出价≈GPT-5.5 的 1/34", "降价 75%"],
      pros: ["真实编码/推理基准贴近 GPT-5.5 / Opus 4.7", "MIT 协议彻底放开商用", "API 价格全行业最低档"],
      cons: ["多模态短板", "官方服务高峰期容量波动", "工具链生态靠社区自建"],
      fit: "成本敏感的一切场景、自部署首选" },
    { name: "Qwen 3.7（Max / Plus）", vendor: "阿里通义", group: "china", access: "开源+闭源", date: "2026.05.20",
      pos: "全尺寸家族 + Agent 硬指标，国产体系化之王",
      specs: ["SWE-Pro 60.6%", "Plus：1M / $0.40 / $1.16", "全尺寸开源家族"],
      pros: ["开源家族从 0.5B 到旗舰全覆盖", "Agent / 编码指标国产最硬", "云上生态与企业服务成熟"],
      cons: ["版本矩阵复杂，选型成本高", "旗舰 Max 不开源"],
      fit: "中文企业级应用、从原型到生产全链路" },
    { name: "Kimi K2.6", vendor: "月之暗面", group: "china", access: "开源", date: "2026.04.20",
      pos: "原生 Agent 平台型模型：Agent Swarm 单次调度 300 子代理",
      specs: ["1T MoE / 32B 激活", "单次 4000 协调动作"],
      pros: ["为多智能体编排而生，长程自主执行激进", "长上下文传统强项", "C 端产品与口碑兼具"],
      cons: ["万亿体量自部署门槛极高", "配套工具链仍在补课"],
      fit: "复杂多 Agent 任务、长文处理、中文 C 端" },
    { name: "GLM-5.1", vendor: "智谱", group: "china", access: "开源", date: "2026.04.07",
      pos: "MIT 开源 + 政企落地最深的工程派",
      specs: ["MIT 协议", "Agent 版 200K 上下文"],
      pros: ["工具调用、定时与持久任务能力专门优化", "政企案例与私有化经验最多", "许可宽松"],
      cons: ["C 端声量弱", "海外生态存在感低"],
      fit: "国内政企私有化、长链执行型 Agent" },
    { name: "豆包 2.0", vendor: "字节跳动", group: "china", access: "闭源", date: "2026.02.14",
      pos: "多模态 Agent 全家桶：Pro / Lite / Mini / Code 四档",
      specs: ["IMO·ICPC 金牌级", "HLE-Text 54.2", "火山引擎分发"],
      pros: ["竞赛级推理成绩 + 视频图像模型家族（Seedance/Seedream）", "抖音生态流量与数据反哺", "分档定价覆盖全场景"],
      cons: ["闭源且开始收费，终结免费时代", "国际化几乎为零"],
      fit: "国内 C 端产品、多模态内容场景" },
    { name: "文心 5.0", vendor: "百度", group: "china", access: "闭源", date: "2026.01.22",
      pos: "2.4 万亿参数的原生全模态统一建模",
      specs: ["2.4T 参数 / 激活 <3%", "全模态理解+生成"],
      pros: ["文本图像音视频统一架构", "中文知识底蕴深", "飞桨自主技术栈"],
      cons: ["开发者生态存在感弱于 Qwen / DeepSeek", "营销分数与社区实测常有温差"],
      fit: "百度云客户、全模态中文场景" },
    { name: "混元 Hy3", vendor: "腾讯", group: "china", access: "开源", date: "2026.04.23",
      pos: "快慢思考融合的务实派，OpenRouter 调用量登顶",
      specs: ["295B MoE / 21B 激活", "上下文 256K", "preview"],
      pros: ["性价比极高，两周调用量超上代 10 倍", "快慢思维融合省 token", "微信生态想象空间"],
      cons: ["仍是 preview，正式版未出", "品牌起步晚，心智弱"],
      fit: "高并发性价比场景、腾讯云用户" },
    { name: "星火 X2", vendor: "科大讯飞", group: "china", access: "闭源", date: "2026.02.11",
      pos: "全国产算力训练的行业纵深玩家",
      specs: ["293B MoE", "AIME 95.7", "130+ 语言"],
      pros: ["算力链路完全自主可控", "教育 / 医疗等行业模型扎实", "多语言覆盖广"],
      cons: ["通用开发者生态薄弱", "C 端产品力一般"],
      fit: "信创与国产化要求、教育医疗行业" },
    { name: "MiniMax M3", vendor: "MiniMax", group: "china", access: "开源", date: "2026.06.01",
      pos: "「原生为 Agent 设计」路线的轻量开源新作",
      specs: ["轻量高效部署", "M2.5 同源 Agent 架构"],
      pros: ["Agent 场景原生优化", "语音 / 视频多模态家族齐全", "部署成本低"],
      cons: ["通用能力与旗舰有差距", "公司多线作战，模型投入分散"],
      fit: "轻量 Agent、语音交互产品" },

    /* ---------- 特化与轻量 ---------- */
    { name: "Devstral 2", vendor: "Mistral", group: "light", access: "开源+API", date: "2025.12",
      pos: "编程特化：单卡 4090 就能跑的本地编码 Agent",
      specs: ["$0.40 / $2.00", "上下文 262K", "Small 版单卡可跑"],
      pros: ["本地部署零 API 成本写代码", "工具调用可靠性 Mistral 系最佳"],
      cons: ["通用推理明显偏科", "已被自家 Medium 3.5 在分数上超越"],
      fit: "数据不能出域的本地编程场景" },
    { name: "Grok 4.1 Fast", vendor: "xAI", group: "light", access: "闭源", date: "2026 初",
      pos: "前沿级里最便宜：$0.20 / $0.50",
      specs: ["$0.20 / $0.50", "Agent 工具支持"],
      pros: ["价格屠夫，批量调用无压力", "企业 API 带 agent 工具"],
      cons: ["深度推理不及旗舰", "xAI 平台稳定性风险连带"],
      fit: "高频轻任务：分类、抽取、摘要流水线" },
    { name: "Mistral Small 4", vendor: "Mistral", group: "light", access: "开源", date: "2026.03.16",
      pos: "三合一小钢炮：推理 + 视觉 + 编码一个模型搞定",
      specs: ["119B MoE / 6B 激活", "$0.15 输入"],
      pros: ["一个模型覆盖三种能力，运维简单", "极便宜"],
      cons: ["每一路能力都非顶尖", "合并后行为调优复杂"],
      fit: "中小团队的「默认模型」、边缘部署" },
    { name: "Gemini 3.5 Flash", vendor: "Google", group: "light", access: "闭源", date: "2026.05.19",
      pos: "大厂轻量速度王，免费层慷慨",
      specs: ["低延迟优化", "免费额度大"],
      pros: ["速度与成本平衡好", "背靠 Gemini 生态无缝升级"],
      cons: ["复杂任务降级明显"],
      fit: "聊天、客服、实时交互场景" },
    { name: "Ministral 3 家族", vendor: "Mistral", group: "light", access: "开源", date: "2026 初",
      pos: "3B / 8B / 14B 端侧三兄弟，手机也能跑",
      specs: ["Apache 2.0", "14B 版 AIME 85"],
      pros: ["端侧 / 离线场景即插即用", "14B 推理版小身材大智慧"],
      cons: ["知识容量天花板低", "长上下文与多模态有限"],
      fit: "端侧 AI、离线应用、隐私敏感设备" }
  ]
};
